// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  DeleteSessionServiceSessionByIdData,
  DeleteSessionServiceSessionByIdErrors,
  DeleteSessionServiceSessionByIdResponses,
  GetChassisData,
  GetChassisErrors,
  GetChassisResponses,
  GetServiceRootData,
  GetServiceRootErrors,
  GetServiceRootResponses,
  GetSessionServiceSessionsData,
  GetSessionServiceSessionsErrors,
  GetSessionServiceSessionsResponses,
  GetSystemsData,
  GetSystemsErrors,
  GetSystemsResponses,
  PostEventServiceSubmitTestEventData,
  PostEventServiceSubmitTestEventErrors,
  PostEventServiceSubmitTestEventResponses,
  PostSessionServiceSessionsData,
  PostSessionServiceSessionsErrors,
  PostSessionServiceSessionsResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const getServiceRoot = <ThrowOnError extends boolean = false>(
  options?: Options<GetServiceRootData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetServiceRootResponses, GetServiceRootErrors, ThrowOnError>({
    responseType: 'json',
    url: '/redfish/v1',
    ...options,
  });

export const getChassis = <ThrowOnError extends boolean = false>(
  options?: Options<GetChassisData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetChassisResponses, GetChassisErrors, ThrowOnError>({
    responseType: 'json',
    url: '/redfish/v1/Chassis',
    ...options,
  });

export const postEventServiceSubmitTestEvent = <ThrowOnError extends boolean = false>(
  options: Options<PostEventServiceSubmitTestEventData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostEventServiceSubmitTestEventResponses,
    PostEventServiceSubmitTestEventErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/redfish/v1/EventService/Actions/EventService.SubmitTestEvent',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getSessionServiceSessions = <ThrowOnError extends boolean = false>(
  options?: Options<GetSessionServiceSessionsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetSessionServiceSessionsResponses,
    GetSessionServiceSessionsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/redfish/v1/SessionService/Sessions',
    ...options,
  });

export const postSessionServiceSessions = <ThrowOnError extends boolean = false>(
  options: Options<PostSessionServiceSessionsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    PostSessionServiceSessionsResponses,
    PostSessionServiceSessionsErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/redfish/v1/SessionService/Sessions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const deleteSessionServiceSessionById = <ThrowOnError extends boolean = false>(
  options: Options<DeleteSessionServiceSessionByIdData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DeleteSessionServiceSessionByIdResponses,
    DeleteSessionServiceSessionByIdErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/redfish/v1/SessionService/Sessions/{SessionId}',
    ...options,
  });

export const getSystems = <ThrowOnError extends boolean = false>(
  options?: Options<GetSystemsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetSystemsResponses, GetSystemsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/redfish/v1/Systems',
    ...options,
  });
