// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};

/**
 * The type of a resource.
 */
export type OdataV4Type = string;

/**
 * The URI to the resource containing the next set of partial members.
 */
export type OdataV4NextLink = string;

/**
 * A reference to a resource.
 */
export type OdataV4IdRef = {
  '@odata.id'?: OdataV4Id;
};

/**
 * The unique identifier for a resource.
 */
export type OdataV4Id = string;

/**
 * The current ETag of the resource.
 */
export type OdataV4Etag = string;

/**
 * The number of items in a collection.
 */
export type OdataV4Count = number;

/**
 * The OData description of a payload.
 */
export type OdataV4Context = string;

/**
 * The base type for an OEM extension.
 */
export type ResourceOemObject = {
  [key: string]: unknown;
};

/**
 * The OEM extension.
 */
export type ResourceOem = {
  [key: string]: unknown;
};

/**
 * The name of the resource or array member.
 */
export type ResourceName = string;

/**
 * The description of this resource.  Used for commonality in the schema definitions.
 */
export type ResourceDescription = string;

export const ResourceHealth = {
  CRITICAL: 'Critical',
  OK: 'OK',
  WARNING: 'Warning',
} as const;

export type ResourceHealth = (typeof ResourceHealth)[keyof typeof ResourceHealth];

/**
 * The information about a parameter included in a Redfish action for this resource.
 */
export type ActionInfoParameters = {
  /**
   * The allowable numeric values or duration values, inclusive ranges of values, and incremental step values for this parameter as applied to this action target.
   */
  readonly AllowableNumbers?: Array<string | null>;
  /**
   * The allowable pattern for this parameter as applied to this action target.
   */
  readonly AllowablePattern?: string | null;
  /**
   * Descriptions of allowable values for this parameter.
   */
  readonly AllowableValueDescriptions?: Array<string | null>;
  /**
   * The allowable values for this parameter as applied to this action target.
   */
  readonly AllowableValues?: Array<string | null>;
  /**
   * The maximum number of array elements allowed for this parameter.
   */
  readonly ArraySizeMaximum?: number | null;
  /**
   * The minimum number of array elements required for this parameter.
   */
  readonly ArraySizeMinimum?: number | null;
  /**
   * The JSON property type for this parameter.
   */
  DataType?: ActionInfoParameterTypes | unknown;
  /**
   * The default value for this parameter.
   */
  readonly DefaultValue?: string | null;
  /**
   * The maximum supported value for this parameter.
   */
  readonly MaximumValue?: number | null;
  /**
   * The minimum supported value for this parameter.
   */
  readonly MinimumValue?: number | null;
  /**
   * The name of the parameter for this action.
   */
  readonly Name: string;
  /**
   * Indicates that there is no default value for this parameter.
   */
  readonly NoDefaultValue?: boolean | null;
  /**
   * The data type of an object-based parameter.
   */
  readonly ObjectDataType?: string | null;
  /**
   * An indication of whether the parameter is required to complete this action.
   */
  readonly Required?: boolean;
};

/**
 * The unique identifier for this resource within the collection of similar resources.
 */
export type ResourceId = string;

/**
 * The message that the Redfish service returns.
 * @version 1.2.1
 */
export type MessageV121Message = {
  /**
   * The human-readable message.
   */
  readonly Message?: string;
  /**
   * An array of message arguments that are substituted for the arguments in the message when looked up in the message registry.
   */
  readonly MessageArgs?: Array<string>;
  /**
   * The identifier for the message.
   */
  readonly MessageId: string;
  MessageSeverity?: ResourceHealth;
  Oem?: ResourceOem;
  /**
   * A set of properties described by the message.
   */
  readonly RelatedProperties?: Array<string>;
  /**
   * Used to provide suggestions on how to resolve the situation that caused the message.
   */
  readonly Resolution?: string;
  /**
   * The list of recommended steps to resolve the situation that caused the message.
   */
  ResolutionSteps?: Array<ResolutionStep>;
  /**
   * The severity of the message.
   *
   * @deprecated
   */
  readonly Severity?: string;
};

/**
 * The error payload from a Redfish service.
 */
export type RedfishError = {
  /**
   * The properties that describe an error from a Redfish service.
   */
  error: {
    /**
     * An array of messages describing one or more error messages.
     */
    '@Message.ExtendedInfo'?: Array<MessageV121Message>;
    /**
     * A string indicating a specific `MessageId` from a message registry.
     */
    readonly code: string;
    /**
     * A human-readable error message corresponding to the message in a message registry.
     */
    readonly message: string;
  };
};

/**
 * @version 1.0.1
 */
export const ResolutionStepResolutionType = {
  COLLECT_DIAGNOSTIC_DATA: 'CollectDiagnosticData',
  CONTACT_VENDOR: 'ContactVendor',
  FIRMWARE_UPDATE: 'FirmwareUpdate',
  OEM: 'OEM',
  POWER_CYCLE: 'PowerCycle',
  REPLACE_COMPONENT: 'ReplaceComponent',
  RESET: 'Reset',
  RESET_TO_DEFAULTS: 'ResetToDefaults',
} as const;

/**
 * @version 1.0.1
 */
export type ResolutionStepResolutionType =
  (typeof ResolutionStepResolutionType)[keyof typeof ResolutionStepResolutionType];

/**
 * @version 1.5.0
 */
export const ActionInfoParameterTypes = {
  BOOLEAN: 'Boolean',
  NUMBER: 'Number',
  NUMBER_ARRAY: 'NumberArray',
  OBJECT: 'Object',
  OBJECT_ARRAY: 'ObjectArray',
  STRING: 'String',
  STRING_ARRAY: 'StringArray',
} as const;

/**
 * @version 1.5.0
 */
export type ActionInfoParameterTypes =
  (typeof ActionInfoParameterTypes)[keyof typeof ActionInfoParameterTypes];

/**
 * This type describes a recommended step of the service-defined resolution.
 */
export type ResolutionStep = {
  /**
   * The parameters of the action URI for a resolution step.
   */
  ActionParameters?: Array<ActionInfoParameters | unknown>;
  /**
   * The action URI for a resolution step.
   */
  readonly ActionURI?: string;
  Oem?: ResourceOem;
  /**
   * The priority in the set of resolution steps.
   */
  readonly Priority?: number | null;
  /**
   * The type of the resolution step.
   */
  ResolutionType: ResolutionStepResolutionType | unknown;
  /**
   * The number of retries for a resolution step.
   */
  readonly RetryCount?: number | null;
  /**
   * The interval between retries for a resolution step.
   */
  readonly RetryIntervalSeconds?: number | null;
  /**
   * The target URI of the component for a resolution step.
   */
  readonly TargetComponentURI?: string | null;
};

/**
 * @version 1.7.4
 */
export const TaskState = {
  COMPLETED: 'Completed',
  EXCEPTION: 'Exception',
  CANCELLING: 'Cancelling',
  INTERRUPTED: 'Interrupted',
  CANCELLED: 'Cancelled',
  NEW: 'New',
  KILLED: 'Killed',
  PENDING: 'Pending',
  RUNNING: 'Running',
  SERVICE: 'Service',
  STARTING: 'Starting',
  STOPPING: 'Stopping',
  SUSPENDED: 'Suspended',
} as const;

/**
 * @version 1.7.4
 */
export type TaskState = (typeof TaskState)[keyof typeof TaskState];

/**
 * The `Task` schema contains information about a task that the Redfish task service schedules or executes.  Tasks represent operations that take more time than a client typically wants to wait.
 * @version 1.7.4
 */
export type Task = {
  '@odata.context'?: OdataV4Context;
  '@odata.etag'?: OdataV4Etag;
  '@odata.id': OdataV4Id;
  '@odata.type': OdataV4Type;
  Actions?: TaskActions;
  Description?: ResourceDescription | unknown;
  /**
   * The date and time when the task was completed.  This property will only appear when the task is complete.
   */
  readonly EndTime?: string;
  /**
   * The estimated total time required to complete the task.
   */
  readonly EstimatedDuration?: string | null;
  /**
   * An indication of whether the contents of the payload are hidden from view after the task has been created.  If `true`, responses do not return the payload.  If `false`, responses return the payload.  If this property is not present when the task is created, the default is `false`.
   */
  readonly HidePayload?: boolean;
  Id: ResourceId;
  Links?: TaskLinks;
  /**
   * An array of messages associated with the task.
   */
  Messages?: Array<Message>;
  Name: ResourceName;
  Oem?: ResourceOem;
  Payload?: TaskPayload;
  /**
   * The completion percentage of this task.
   */
  readonly PercentComplete?: number | null;
  /**
   * The date and time when the task was started.
   */
  readonly StartTime?: string;
  SubTasks?: OdataV4IdRef;
  /**
   * The URI of the task monitor for this task.
   */
  readonly TaskMonitor?: string;
  TaskState?: TaskState;
  TaskStatus?: ResourceHealth;
};

/**
 * The HTTP and JSON payload details for this Task.
 * @version 1.7.4
 */
export type TaskPayload = {
  /**
   * An array of HTTP headers that this task includes.
   */
  readonly HttpHeaders?: Array<string>;
  /**
   * The HTTP operation to perform to execute this task.
   */
  readonly HttpOperation?: string;
  /**
   * The JSON payload to use in the execution of this task.
   */
  readonly JsonBody?: string;
  /**
   * The URI of the target for this task.
   */
  readonly TargetUri?: string;
};

/**
 * The message that the Redfish service returns.
 */
export type Message = {
  /**
   * The human-readable message.
   */
  readonly Message?: string;
  /**
   * An array of message arguments that are substituted for the arguments in the message when looked up in the message registry.
   */
  readonly MessageArgs?: Array<string>;
  /**
   * The identifier for the message.
   */
  readonly MessageId: string;
  MessageSeverity?: ResourceHealth;
  Oem?: ResourceOem;
  /**
   * A set of properties described by the message.
   */
  readonly RelatedProperties?: Array<string>;
  /**
   * Used to provide suggestions on how to resolve the situation that caused the message.
   */
  readonly Resolution?: string;
  /**
   * The list of recommended steps to resolve the situation that caused the message.
   */
  ResolutionSteps?: Array<ResolutionStep>;
  /**
   * The severity of the message.
   *
   * @deprecated
   */
  readonly Severity?: string;
  /**
   * The source of authentication for the username property associated with the message.
   */
  readonly UserAuthenticationSource?: string | null;
  /**
   * The username of the account associated with the message.
   */
  readonly Username?: string | null;
};

/**
 * The links to other resources that are related to this resource.
 * @version 1.7.4
 */
export type TaskLinks = {
  /**
   * An array of URIs referencing the resources created as the result of the operation that produced this task.
   */
  readonly CreatedResources?: Array<OdataV4IdRef>;
  'CreatedResources@odata.count'?: OdataV4Count;
  Oem?: ResourceOem;
};

/**
 * The available OEM-specific actions for this resource.
 * @version 1.7.4
 */
export type TaskOemActions = {
  [key: string]: unknown;
};

/**
 * The available actions for this resource.
 * @version 1.7.4
 */
export type TaskActions = {
  Oem?: TaskOemActions;
};

/**
 * The collection of `Session` resource instances.
 */
export type SessionCollection = {
  '@odata.context'?: OdataV4Context;
  '@odata.etag'?: OdataV4Etag;
  '@odata.id': OdataV4Id;
  '@odata.type': OdataV4Type;
  Description?: ResourceDescription | unknown;
  /**
   * The members of this collection.
   */
  readonly Members: Array<OdataV4IdRef>;
  'Members@odata.count': OdataV4Count;
  'Members@odata.nextLink'?: OdataV4NextLink;
  Name: ResourceName;
  Oem?: ResourceOem;
};

/**
 * @version 1.8.0
 */
export const SessionTypes = {
  HOST_CONSOLE: 'HostConsole',
  IPMI: 'IPMI',
  KVMIP: 'KVMIP',
  MANAGER_CONSOLE: 'ManagerConsole',
  OEM: 'OEM',
  OUTBOUND_CONNECTION: 'OutboundConnection',
  REDFISH: 'Redfish',
  VIRTUAL_MEDIA: 'VirtualMedia',
  WEB_UI: 'WebUI',
} as const;

/**
 * @version 1.8.0
 */
export type SessionTypes = (typeof SessionTypes)[keyof typeof SessionTypes];

/**
 * The `Session` resource describes a single connection (session) between a client and a Redfish service instance.
 * @version 1.8.0
 */
export type Session = {
  '@odata.context'?: OdataV4Context;
  '@odata.etag'?: OdataV4Etag;
  '@odata.id': OdataV4Id;
  '@odata.type': OdataV4Type;
  Actions?: SessionActions;
  /**
   * The IP address of the client that created the session.
   */
  readonly ClientOriginIPAddress?: string | null;
  /**
   * A client-supplied string that is stored with the session.
   */
  readonly Context?: string | null;
  /**
   * The date and time when the session was created.
   */
  readonly CreatedTime?: string | null;
  Description?: ResourceDescription | unknown;
  /**
   * The date and time when the session expires regardless of session activity.
   */
  readonly ExpirationTime?: string;
  Id: ResourceId;
  Links?: SessionLinks;
  Name: ResourceName;
  Oem?: ResourceOem;
  /**
   * The active OEM-defined session type.
   */
  readonly OemSessionType?: string | null;
  /**
   * The password for this session.  The value is `null` in responses.
   */
  Password?: string | null;
  /**
   * The Redfish roles that contain the privileges of this session.
   */
  readonly Roles?: Array<string | null>;
  /**
   * The active session type.
   */
  SessionType?: SessionTypes | unknown;
  /**
   * The multi-factor authentication token for this session.  The value is `null` in responses.
   */
  Token?: string | null;
  /**
   * The username for the account for this session.
   */
  UserName?: string | null;
};

/**
 * The links to other resources that are related to this resource.
 * @version 1.8.0
 */
export type SessionLinks = {
  Oem?: ResourceOem;
  OutboundConnection?: OdataV4IdRef;
};

/**
 * The available OEM-specific actions for this resource.
 * @version 1.8.0
 */
export type SessionOemActions = {
  [key: string]: unknown;
};

/**
 * The available actions for this resource.
 * @version 1.8.0
 */
export type SessionActions = {
  Oem?: SessionOemActions;
};

/**
 * The `ServiceRoot` schema describes the root of the Redfish service, located at the '/redfish/v1' URI.  All other resources accessible through the Redfish interface on this device are linked directly or indirectly from the service root.
 * @version 1.20.0
 */
export type ServiceRoot = {
  '@odata.context'?: OdataV4Context;
  '@odata.etag'?: OdataV4Etag;
  '@odata.id': OdataV4Id;
  '@odata.type': OdataV4Type;
  AccountService?: OdataV4IdRef;
  AggregationService?: OdataV4IdRef;
  AutomationNodes?: OdataV4IdRef;
  Cables?: OdataV4IdRef;
  CertificateService?: OdataV4IdRef;
  Chassis?: OdataV4IdRef;
  ComponentIntegrity?: OdataV4IdRef;
  CompositionService?: OdataV4IdRef;
  Description?: ResourceDescription | unknown;
  EventService?: OdataV4IdRef;
  Fabrics?: OdataV4IdRef;
  Facilities?: OdataV4IdRef;
  Id: ResourceId;
  JobService?: OdataV4IdRef;
  JsonSchemas?: OdataV4IdRef;
  KeyService?: OdataV4IdRef;
  LicenseService?: OdataV4IdRef;
  Links: ServiceRootLinks;
  Managers?: OdataV4IdRef;
  NVMeDomains?: OdataV4IdRef;
  Name: ResourceName;
  Oem?: ResourceOem;
  PowerEquipment?: OdataV4IdRef;
  /**
   * The product associated with this Redfish service.
   */
  readonly Product?: string | null;
  ProtocolFeaturesSupported?: ServiceRootProtocolFeaturesSupported;
  /**
   * The version of the Redfish service.
   */
  readonly RedfishVersion?: string;
  RegisteredClients?: OdataV4IdRef;
  Registries?: OdataV4IdRef;
  ResourceBlocks?: OdataV4IdRef;
  ServiceConditions?: OdataV4IdRef;
  /**
   * The vendor or user-provided product and service identifier.
   */
  readonly ServiceIdentification?: string;
  /**
   * The usage notification message for this service.
   */
  readonly ServiceUseNotification?: string;
  SessionService?: OdataV4IdRef;
  Storage?: OdataV4IdRef;
  StorageServices?: OdataV4IdRef;
  StorageSystems?: OdataV4IdRef;
  Systems?: OdataV4IdRef;
  Tasks?: OdataV4IdRef;
  TelemetryService?: OdataV4IdRef;
  ThermalEquipment?: OdataV4IdRef;
  /**
   * Unique identifier for a service instance.  When SSDP is used, this value contains the same UUID returned in an HTTP `200 OK` response from an SSDP `M-SEARCH` request during discovery.
   */
  readonly UUID?: string | null;
  UpdateService?: OdataV4IdRef;
  /**
   * The vendor or manufacturer associated with this Redfish service.
   */
  readonly Vendor?: string | null;
};

/**
 * The information about the use of `$expand` in the service.
 * @version 1.20.0
 */
export type ServiceRootExpand = {
  /**
   * An indication of whether the service supports the asterisk (`*`) option of the `$expand` query parameter.
   */
  readonly ExpandAll?: boolean;
  /**
   * An indication of whether the service supports the `$levels` option of the `$expand` query parameter.
   */
  readonly Levels?: boolean;
  /**
   * An indication of whether this service supports the tilde (`~`) option of the `$expand` query parameter.
   */
  readonly Links?: boolean;
  /**
   * The maximum `$levels` option value in the `$expand` query parameter.
   */
  readonly MaxLevels?: number;
  /**
   * An indication of whether the service supports the period (`.`) option of the `$expand` query parameter.
   */
  readonly NoLinks?: boolean;
};

/**
 * The information about deep operations that the service supports.
 * @version 1.20.0
 */
export type ServiceRootDeepOperations = {
  /**
   * An indication of whether the service supports the deep `PATCH` operation.
   */
  readonly DeepPATCH?: boolean;
  /**
   * An indication of whether the service supports the deep `POST` operation.
   */
  readonly DeepPOST?: boolean;
  /**
   * The maximum levels of resources allowed in deep operations.
   */
  readonly MaxLevels?: number;
};

/**
 * The information about protocol features that the service supports.
 * @version 1.20.0
 */
export type ServiceRootProtocolFeaturesSupported = {
  DeepOperations?: ServiceRootDeepOperations;
  /**
   * An indication of whether the service supports the `excerpt` query parameter.
   */
  readonly ExcerptQuery?: boolean;
  ExpandQuery?: ServiceRootExpand;
  /**
   * An indication of whether the service supports the `$filter` query parameter.
   */
  readonly FilterQuery?: boolean;
  /**
   * An indication of whether the service supports the `eq`, `ge`, `gt`, `le`, `lt`, and `ne` options for the `$filter` query parameter.
   */
  readonly FilterQueryComparisonOperations?: boolean;
  /**
   * An indication of whether the service supports the `()`, `and`, `not`, and `or` options for the `$filter` query parameter.
   */
  readonly FilterQueryCompoundOperations?: boolean;
  /**
   * An indication of whether the service supports the `includeoriginofcondition` query parameter.
   */
  readonly IncludeOriginOfConditionQuery?: boolean;
  /**
   * An indication of whether the service supports multiple outstanding HTTP requests.
   */
  readonly MultipleHTTPRequests?: boolean;
  /**
   * An indication of whether the service supports the `only` query parameter.
   */
  readonly OnlyMemberQuery?: boolean;
  /**
   * An indication of whether the service supports the `$select` query parameter.
   */
  readonly SelectQuery?: boolean;
  /**
   * An indication of whether the service supports both the `$top` and `$skip` query parameters.
   */
  readonly TopSkipQuery?: boolean;
};

/**
 * The links to other resources that are related to this resource.
 * @version 1.20.0
 */
export type ServiceRootLinks = {
  ManagerProvidingService?: OdataV4IdRef;
  Oem?: ResourceOem;
  Sessions: OdataV4IdRef;
};

/**
 * @deprecated
 */
export const EventType = {
  ALERT: 'Alert',
  METRIC_REPORT: 'MetricReport',
  OTHER: 'Other',
  RESOURCE_ADDED: 'ResourceAdded',
  RESOURCE_REMOVED: 'ResourceRemoved',
  RESOURCE_UPDATED: 'ResourceUpdated',
  STATUS_CHANGE: 'StatusChange',
} as const;

/**
 * @deprecated
 */
export type EventType = (typeof EventType)[keyof typeof EventType];

/**
 * This action generates a test event.
 * @version 1.12.0
 */
export type EventServiceSubmitTestEventRequestBody = {
  /**
   * The group identifier for the event.
   */
  EventGroupId?: number;
  /**
   * The ID for the event to add.
   */
  EventId?: string;
  /**
   * The date and time for the event to add.
   */
  EventTimestamp?: string;
  EventType?: EventType;
  /**
   * The human-readable message for the event to add.
   */
  Message?: string;
  /**
   * An array of message arguments for the event to add.
   */
  MessageArgs?: Array<string>;
  /**
   * The `MessageId` for the event to add.
   */
  MessageId: string;
  MessageSeverity?: ResourceHealth;
  /**
   * The URL in the `OriginOfCondition` property of the event to add.  It is not a reference object.
   */
  OriginOfCondition?: string;
  /**
   * The severity for the event to add.
   */
  Severity?: string;
};

/**
 * The collection of `ComputerSystem` resource instances.
 */
export type ComputerSystemCollection = {
  '@odata.context'?: OdataV4Context;
  '@odata.etag'?: OdataV4Etag;
  '@odata.id': OdataV4Id;
  '@odata.type': OdataV4Type;
  Description?: ResourceDescription | unknown;
  /**
   * The members of this collection.
   */
  readonly Members: Array<OdataV4IdRef>;
  'Members@odata.count': OdataV4Count;
  'Members@odata.nextLink'?: OdataV4NextLink;
  Name: ResourceName;
  Oem?: ResourceOem;
};

/**
 * The collection of `Chassis` resource instances.
 */
export type ChassisCollection = {
  '@odata.context'?: OdataV4Context;
  '@odata.etag'?: OdataV4Etag;
  '@odata.id': OdataV4Id;
  '@odata.type': OdataV4Type;
  Description?: ResourceDescription | unknown;
  /**
   * The members of this collection.
   */
  readonly Members: Array<OdataV4IdRef>;
  'Members@odata.count': OdataV4Count;
  'Members@odata.nextLink'?: OdataV4NextLink;
  Name: ResourceName;
  Oem?: ResourceOem;
};

/**
 * A reference to a resource.
 */
export type OdataV4IdRefWritable = {
  [key: string]: never;
};

/**
 * The base type for an OEM extension.
 */
export type ResourceOemObjectWritable = {
  [key: string]: unknown;
};

/**
 * The OEM extension.
 */
export type ResourceOemWritable = {
  [key: string]: unknown;
};

/**
 * The message that the Redfish service returns.
 * @version 1.2.1
 */
export type MessageV121MessageWritable = {
  Oem?: ResourceOemWritable;
  /**
   * The list of recommended steps to resolve the situation that caused the message.
   */
  ResolutionSteps?: Array<ResolutionStepWritable>;
};

/**
 * The error payload from a Redfish service.
 */
export type RedfishErrorWritable = {
  /**
   * The properties that describe an error from a Redfish service.
   */
  error: {
    /**
     * An array of messages describing one or more error messages.
     */
    '@Message.ExtendedInfo'?: Array<MessageV121MessageWritable>;
  };
};

/**
 * This type describes a recommended step of the service-defined resolution.
 */
export type ResolutionStepWritable = {
  /**
   * The parameters of the action URI for a resolution step.
   */
  ActionParameters?: Array<unknown>;
  Oem?: ResourceOemWritable;
};

/**
 * The `Task` schema contains information about a task that the Redfish task service schedules or executes.  Tasks represent operations that take more time than a client typically wants to wait.
 * @version 1.7.4
 */
export type TaskWritable = {
  Actions?: TaskActions;
  Links?: TaskLinksWritable;
  /**
   * An array of messages associated with the task.
   */
  Messages?: Array<MessageWritable>;
  Oem?: ResourceOemWritable;
};

/**
 * The message that the Redfish service returns.
 */
export type MessageWritable = {
  Oem?: ResourceOemWritable;
  /**
   * The list of recommended steps to resolve the situation that caused the message.
   */
  ResolutionSteps?: Array<ResolutionStepWritable>;
};

/**
 * The links to other resources that are related to this resource.
 * @version 1.7.4
 */
export type TaskLinksWritable = {
  Oem?: ResourceOemWritable;
};

/**
 * The available OEM-specific actions for this resource.
 * @version 1.7.4
 */
export type TaskOemActionsWritable = {
  [key: string]: unknown;
};

/**
 * The collection of `Session` resource instances.
 */
export type SessionCollectionWritable = {
  Oem?: ResourceOemWritable;
};

/**
 * The `Session` resource describes a single connection (session) between a client and a Redfish service instance.
 * @version 1.8.0
 */
export type SessionWritable = {
  Actions?: SessionActions;
  Links?: SessionLinksWritable;
  Oem?: ResourceOemWritable;
  /**
   * The password for this session.  The value is `null` in responses.
   */
  Password?: string | null;
  /**
   * The multi-factor authentication token for this session.  The value is `null` in responses.
   */
  Token?: string | null;
  /**
   * The username for the account for this session.
   */
  UserName?: string | null;
};

/**
 * The links to other resources that are related to this resource.
 * @version 1.8.0
 */
export type SessionLinksWritable = {
  Oem?: ResourceOemWritable;
};

/**
 * The available OEM-specific actions for this resource.
 * @version 1.8.0
 */
export type SessionOemActionsWritable = {
  [key: string]: unknown;
};

/**
 * The `ServiceRoot` schema describes the root of the Redfish service, located at the '/redfish/v1' URI.  All other resources accessible through the Redfish interface on this device are linked directly or indirectly from the service root.
 * @version 1.20.0
 */
export type ServiceRootWritable = {
  Links: ServiceRootLinksWritable;
  Oem?: ResourceOemWritable;
  ProtocolFeaturesSupported?: ServiceRootProtocolFeaturesSupportedWritable;
};

/**
 * The information about protocol features that the service supports.
 * @version 1.20.0
 */
export type ServiceRootProtocolFeaturesSupportedWritable = {
  [key: string]: never;
};

/**
 * The links to other resources that are related to this resource.
 * @version 1.20.0
 */
export type ServiceRootLinksWritable = {
  Oem?: ResourceOemWritable;
};

/**
 * The collection of `ComputerSystem` resource instances.
 */
export type ComputerSystemCollectionWritable = {
  Oem?: ResourceOemWritable;
};

/**
 * The collection of `Chassis` resource instances.
 */
export type ChassisCollectionWritable = {
  Oem?: ResourceOemWritable;
};

/**
 * Include origin-of-condition data when returning condition information.
 */
export type RedfishQueryParamIncludeoriginofcondition = string;

/**
 * Redfish query option to request an excerpted payload.
 */
export type RedfishQueryParamExcerpt = string;

/**
 * Redfish query option to request only selected payload sections.
 */
export type RedfishQueryParamOnly = string;

/**
 * Skip a number of collection members before returning results.
 */
export type RedfishQueryParamSkip = number;

/**
 * Limit the number of collection members returned.
 */
export type RedfishQueryParamTop = number;

/**
 * Filter collection members using an OData filter expression.
 */
export type RedfishQueryParamFilter = string;

/**
 * Select a subset of properties to include in the response.
 */
export type RedfishQueryParamSelect = string;

/**
 * Expand related resources per OData URL conventions.
 */
export type RedfishQueryParamExpand = string;

export type GetServiceRootData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Expand related resources per OData URL conventions.
     */
    $expand?: string;
    /**
     * Filter collection members using an OData filter expression.
     */
    $filter?: string;
    /**
     * Select a subset of properties to include in the response.
     */
    $select?: string;
    /**
     * Skip a number of collection members before returning results.
     */
    $skip?: number;
    /**
     * Limit the number of collection members returned.
     */
    $top?: number;
    /**
     * Redfish query option to request an excerpted payload.
     */
    excerpt?: string;
    /**
     * Include origin-of-condition data when returning condition information.
     */
    includeoriginofcondition?: string;
    /**
     * Redfish query option to request only selected payload sections.
     */
    only?: string;
  };
  url: '/redfish/v1';
};

export type GetServiceRootErrors = {
  /**
   * Error condition
   */
  default: RedfishError;
};

export type GetServiceRootError = GetServiceRootErrors[keyof GetServiceRootErrors];

export type GetServiceRootResponses = {
  /**
   * The response contains a representation of the ServiceRoot resource
   */
  200: ServiceRoot;
};

export type GetServiceRootResponse = GetServiceRootResponses[keyof GetServiceRootResponses];

export type GetChassisData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Expand related resources per OData URL conventions.
     */
    $expand?: string;
    /**
     * Filter collection members using an OData filter expression.
     */
    $filter?: string;
    /**
     * Select a subset of properties to include in the response.
     */
    $select?: string;
    /**
     * Skip a number of collection members before returning results.
     */
    $skip?: number;
    /**
     * Limit the number of collection members returned.
     */
    $top?: number;
    /**
     * Redfish query option to request an excerpted payload.
     */
    excerpt?: string;
    /**
     * Include origin-of-condition data when returning condition information.
     */
    includeoriginofcondition?: string;
    /**
     * Redfish query option to request only selected payload sections.
     */
    only?: string;
  };
  url: '/redfish/v1/Chassis';
};

export type GetChassisErrors = {
  /**
   * Error condition
   */
  default: RedfishError;
};

export type GetChassisError = GetChassisErrors[keyof GetChassisErrors];

export type GetChassisResponses = {
  /**
   * The response contains a representation of the ChassisCollection resource
   */
  200: ChassisCollection;
};

export type GetChassisResponse = GetChassisResponses[keyof GetChassisResponses];

export type PostEventServiceSubmitTestEventData = {
  body: EventServiceSubmitTestEventRequestBody;
  path?: never;
  query?: never;
  url: '/redfish/v1/EventService/Actions/EventService.SubmitTestEvent';
};

export type PostEventServiceSubmitTestEventErrors = {
  /**
   * Error condition
   */
  default: RedfishError;
};

export type PostEventServiceSubmitTestEventError =
  PostEventServiceSubmitTestEventErrors[keyof PostEventServiceSubmitTestEventErrors];

export type PostEventServiceSubmitTestEventResponses = {
  /**
   * The response contains the results of the SubmitTestEvent action
   */
  200: RedfishError;
  /**
   * The response contains the results of the SubmitTestEvent action
   */
  201: RedfishError;
  /**
   * Accepted; a task has been generated
   */
  202: Task;
  /**
   * Success, but no response data
   */
  204: void;
};

export type PostEventServiceSubmitTestEventResponse =
  PostEventServiceSubmitTestEventResponses[keyof PostEventServiceSubmitTestEventResponses];

export type GetSessionServiceSessionsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Expand related resources per OData URL conventions.
     */
    $expand?: string;
    /**
     * Filter collection members using an OData filter expression.
     */
    $filter?: string;
    /**
     * Select a subset of properties to include in the response.
     */
    $select?: string;
    /**
     * Skip a number of collection members before returning results.
     */
    $skip?: number;
    /**
     * Limit the number of collection members returned.
     */
    $top?: number;
    /**
     * Redfish query option to request an excerpted payload.
     */
    excerpt?: string;
    /**
     * Include origin-of-condition data when returning condition information.
     */
    includeoriginofcondition?: string;
    /**
     * Redfish query option to request only selected payload sections.
     */
    only?: string;
  };
  url: '/redfish/v1/SessionService/Sessions';
};

export type GetSessionServiceSessionsErrors = {
  /**
   * Error condition
   */
  default: RedfishError;
};

export type GetSessionServiceSessionsError =
  GetSessionServiceSessionsErrors[keyof GetSessionServiceSessionsErrors];

export type GetSessionServiceSessionsResponses = {
  /**
   * The response contains a representation of the SessionCollection resource
   */
  200: SessionCollection;
};

export type GetSessionServiceSessionsResponse =
  GetSessionServiceSessionsResponses[keyof GetSessionServiceSessionsResponses];

export type PostSessionServiceSessionsData = {
  body: SessionWritable;
  path?: never;
  query?: never;
  url: '/redfish/v1/SessionService/Sessions';
};

export type PostSessionServiceSessionsErrors = {
  /**
   * Error condition
   */
  default: RedfishError;
};

export type PostSessionServiceSessionsError =
  PostSessionServiceSessionsErrors[keyof PostSessionServiceSessionsErrors];

export type PostSessionServiceSessionsResponses = {
  /**
   * A resource of type Session has been created
   */
  201: Session;
  /**
   * Accepted; a task has been generated
   */
  202: Task;
  /**
   * Success, but no response data
   */
  204: void;
};

export type PostSessionServiceSessionsResponse =
  PostSessionServiceSessionsResponses[keyof PostSessionServiceSessionsResponses];

export type DeleteSessionServiceSessionByIdData = {
  body?: never;
  path: {
    /**
     * The value of the Id property of the Session resource
     */
    SessionId: string;
  };
  query?: never;
  url: '/redfish/v1/SessionService/Sessions/{SessionId}';
};

export type DeleteSessionServiceSessionByIdErrors = {
  /**
   * Error condition
   */
  default: RedfishError;
};

export type DeleteSessionServiceSessionByIdError =
  DeleteSessionServiceSessionByIdErrors[keyof DeleteSessionServiceSessionByIdErrors];

export type DeleteSessionServiceSessionByIdResponses = {
  /**
   * The response contains a representation of the Session resource
   */
  200: Session;
  /**
   * Accepted; a task has been generated
   */
  202: Task;
  /**
   * Success, but no response data
   */
  204: void;
};

export type DeleteSessionServiceSessionByIdResponse =
  DeleteSessionServiceSessionByIdResponses[keyof DeleteSessionServiceSessionByIdResponses];

export type GetSystemsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Expand related resources per OData URL conventions.
     */
    $expand?: string;
    /**
     * Filter collection members using an OData filter expression.
     */
    $filter?: string;
    /**
     * Select a subset of properties to include in the response.
     */
    $select?: string;
    /**
     * Skip a number of collection members before returning results.
     */
    $skip?: number;
    /**
     * Limit the number of collection members returned.
     */
    $top?: number;
    /**
     * Redfish query option to request an excerpted payload.
     */
    excerpt?: string;
    /**
     * Include origin-of-condition data when returning condition information.
     */
    includeoriginofcondition?: string;
    /**
     * Redfish query option to request only selected payload sections.
     */
    only?: string;
  };
  url: '/redfish/v1/Systems';
};

export type GetSystemsErrors = {
  /**
   * Error condition
   */
  default: RedfishError;
};

export type GetSystemsError = GetSystemsErrors[keyof GetSystemsErrors];

export type GetSystemsResponses = {
  /**
   * The response contains a representation of the ComputerSystemCollection resource
   */
  200: ComputerSystemCollection;
};

export type GetSystemsResponse = GetSystemsResponses[keyof GetSystemsResponses];
