// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/vue-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import {
  deleteSessionServiceSessionById,
  getAccountServiceAccountById,
  getChassis,
  getServiceRoot,
  getSessionServiceSessions,
  getSystemById,
  getSystems,
  getTelemetryServiceMetricReportById,
  getTelemetryServiceMetricReports,
  type Options,
  postEventServiceSubmitTestEvent,
  postSessionServiceSessions,
  postSystemReset,
} from '../sdk.gen';
import type {
  DeleteSessionServiceSessionByIdData,
  DeleteSessionServiceSessionByIdError,
  DeleteSessionServiceSessionByIdResponse,
  GetAccountServiceAccountByIdData,
  GetAccountServiceAccountByIdError,
  GetAccountServiceAccountByIdResponse,
  GetChassisData,
  GetChassisError,
  GetChassisResponse,
  GetServiceRootData,
  GetServiceRootError,
  GetServiceRootResponse,
  GetSessionServiceSessionsData,
  GetSessionServiceSessionsError,
  GetSessionServiceSessionsResponse,
  GetSystemByIdData,
  GetSystemByIdError,
  GetSystemByIdResponse,
  GetSystemsData,
  GetSystemsError,
  GetSystemsResponse,
  GetTelemetryServiceMetricReportByIdData,
  GetTelemetryServiceMetricReportByIdError,
  GetTelemetryServiceMetricReportByIdResponse,
  GetTelemetryServiceMetricReportsData,
  GetTelemetryServiceMetricReportsError,
  GetTelemetryServiceMetricReportsResponse,
  PostEventServiceSubmitTestEventData,
  PostEventServiceSubmitTestEventError,
  PostEventServiceSubmitTestEventResponse,
  PostSessionServiceSessionsData,
  PostSessionServiceSessionsError,
  PostSessionServiceSessionsResponse,
  PostSystemResetData,
  PostSystemResetError,
  PostSystemResetResponse,
} from '../types.gen';

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const getServiceRootQueryKey = (options?: Options<GetServiceRootData>) =>
  createQueryKey('getServiceRoot', options);

export const getServiceRootOptions = (options?: Options<GetServiceRootData>) =>
  queryOptions<
    GetServiceRootResponse,
    AxiosError<GetServiceRootError>,
    GetServiceRootResponse,
    ReturnType<typeof getServiceRootQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getServiceRoot({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getServiceRootQueryKey(options),
  });

export const getAccountServiceAccountByIdQueryKey = (
  options: Options<GetAccountServiceAccountByIdData>,
) => createQueryKey('getAccountServiceAccountById', options);

export const getAccountServiceAccountByIdOptions = (
  options: Options<GetAccountServiceAccountByIdData>,
) =>
  queryOptions<
    GetAccountServiceAccountByIdResponse,
    AxiosError<GetAccountServiceAccountByIdError>,
    GetAccountServiceAccountByIdResponse,
    ReturnType<typeof getAccountServiceAccountByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAccountServiceAccountById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAccountServiceAccountByIdQueryKey(options),
  });

export const getChassisQueryKey = (options?: Options<GetChassisData>) =>
  createQueryKey('getChassis', options);

export const getChassisOptions = (options?: Options<GetChassisData>) =>
  queryOptions<
    GetChassisResponse,
    AxiosError<GetChassisError>,
    GetChassisResponse,
    ReturnType<typeof getChassisQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getChassis({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getChassisQueryKey(options),
  });

export const postEventServiceSubmitTestEventMutation = (
  options?: Partial<Options<PostEventServiceSubmitTestEventData>>,
): UseMutationOptions<
  PostEventServiceSubmitTestEventResponse,
  AxiosError<PostEventServiceSubmitTestEventError>,
  Options<PostEventServiceSubmitTestEventData>
> => {
  const mutationOptions: UseMutationOptions<
    PostEventServiceSubmitTestEventResponse,
    AxiosError<PostEventServiceSubmitTestEventError>,
    Options<PostEventServiceSubmitTestEventData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postEventServiceSubmitTestEvent({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getSessionServiceSessionsQueryKey = (
  options?: Options<GetSessionServiceSessionsData>,
) => createQueryKey('getSessionServiceSessions', options);

export const getSessionServiceSessionsOptions = (
  options?: Options<GetSessionServiceSessionsData>,
) =>
  queryOptions<
    GetSessionServiceSessionsResponse,
    AxiosError<GetSessionServiceSessionsError>,
    GetSessionServiceSessionsResponse,
    ReturnType<typeof getSessionServiceSessionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSessionServiceSessions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSessionServiceSessionsQueryKey(options),
  });

export const postSessionServiceSessionsMutation = (
  options?: Partial<Options<PostSessionServiceSessionsData>>,
): UseMutationOptions<
  PostSessionServiceSessionsResponse,
  AxiosError<PostSessionServiceSessionsError>,
  Options<PostSessionServiceSessionsData>
> => {
  const mutationOptions: UseMutationOptions<
    PostSessionServiceSessionsResponse,
    AxiosError<PostSessionServiceSessionsError>,
    Options<PostSessionServiceSessionsData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postSessionServiceSessions({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const deleteSessionServiceSessionByIdMutation = (
  options?: Partial<Options<DeleteSessionServiceSessionByIdData>>,
): UseMutationOptions<
  DeleteSessionServiceSessionByIdResponse,
  AxiosError<DeleteSessionServiceSessionByIdError>,
  Options<DeleteSessionServiceSessionByIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteSessionServiceSessionByIdResponse,
    AxiosError<DeleteSessionServiceSessionByIdError>,
    Options<DeleteSessionServiceSessionByIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteSessionServiceSessionById({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getSystemsQueryKey = (options?: Options<GetSystemsData>) =>
  createQueryKey('getSystems', options);

export const getSystemsOptions = (options?: Options<GetSystemsData>) =>
  queryOptions<
    GetSystemsResponse,
    AxiosError<GetSystemsError>,
    GetSystemsResponse,
    ReturnType<typeof getSystemsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSystems({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSystemsQueryKey(options),
  });

export const getSystemByIdQueryKey = (options: Options<GetSystemByIdData>) =>
  createQueryKey('getSystemById', options);

export const getSystemByIdOptions = (options: Options<GetSystemByIdData>) =>
  queryOptions<
    GetSystemByIdResponse,
    AxiosError<GetSystemByIdError>,
    GetSystemByIdResponse,
    ReturnType<typeof getSystemByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSystemById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSystemByIdQueryKey(options),
  });

export const postSystemResetMutation = (
  options?: Partial<Options<PostSystemResetData>>,
): UseMutationOptions<
  PostSystemResetResponse,
  AxiosError<PostSystemResetError>,
  Options<PostSystemResetData>
> => {
  const mutationOptions: UseMutationOptions<
    PostSystemResetResponse,
    AxiosError<PostSystemResetError>,
    Options<PostSystemResetData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postSystemReset({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getTelemetryServiceMetricReportsQueryKey = (
  options?: Options<GetTelemetryServiceMetricReportsData>,
) => createQueryKey('getTelemetryServiceMetricReports', options);

export const getTelemetryServiceMetricReportsOptions = (
  options?: Options<GetTelemetryServiceMetricReportsData>,
) =>
  queryOptions<
    GetTelemetryServiceMetricReportsResponse,
    AxiosError<GetTelemetryServiceMetricReportsError>,
    GetTelemetryServiceMetricReportsResponse,
    ReturnType<typeof getTelemetryServiceMetricReportsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTelemetryServiceMetricReports({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTelemetryServiceMetricReportsQueryKey(options),
  });

export const getTelemetryServiceMetricReportByIdQueryKey = (
  options: Options<GetTelemetryServiceMetricReportByIdData>,
) => createQueryKey('getTelemetryServiceMetricReportById', options);

export const getTelemetryServiceMetricReportByIdOptions = (
  options: Options<GetTelemetryServiceMetricReportByIdData>,
) =>
  queryOptions<
    GetTelemetryServiceMetricReportByIdResponse,
    AxiosError<GetTelemetryServiceMetricReportByIdError>,
    GetTelemetryServiceMetricReportByIdResponse,
    ReturnType<typeof getTelemetryServiceMetricReportByIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTelemetryServiceMetricReportById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTelemetryServiceMetricReportByIdQueryKey(options),
  });
